version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  make-new-release:
    docker:
      - image: cimg/python:3.8.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - install-gh-cli
      - run:
          name: Create release
          command: |
            RELEASE_VERSION=$(poetry version --short)
            gh release create $RELEASE_VERSION --generate-notes

  docs-build:
      docker:
        - image: cimg/python:3.8.12
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: poetry
        - run: |
            poetry run sphinx-apidoc evolutionary_optimization -o docs/source
            cd docs && poetry run make html
        - persist_to_workspace:
            root: docs/build/
            paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/build
      - run:
          name: Disable jekyll builds
          command: touch docs/build/html/.nojekyll
      - run:
          name: Upload docs to gh-pages branch
          command: |
            git checkout gh-pages
            git add docs/build/html
            git commit -m "Updating sphinx documentation"
            git push -u origin gh-pages
#      - run:
#          name: Install and configure dependencies
#          command: |
#            npm install -g --silent gh-pages@2.0.1
#            git config user.email "mswolinska@gmail.com"
#            git config user.name "mwolinska"
#      - add_ssh_keys:
#          fingerprints:
#            - "a3:39:98:59:ae:db:a0:f6:0d:99:6c:2b:bb:20:57:da"
#      - run:
#          name: Deploy docs to gh-pages branch
#          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/build/html


workflows:
  main:
    jobs:
      - make-new-release:
          filters:
            branches:
              only:
                - master
                - main
          context:
            - GITHUB_CREDS
      - docs-build:
          filters:
            branches:
              only:
                set_up_sphinx_documentation
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: set_up_sphinx_documentation


commands:
  install-gh-cli:
    description: Install Github CLI
    steps:
      - run:
          name: Get and install gh-cli
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
